// Copyright (c) 2022 Jonathan Lang

//---------- ----------------------------- ----------
//---------- !!! AUTOGENERATED CONTENT !!! ----------
//---------- ----------------------------- ----------

//Runtime Monitoring
//File generated: 2023-03-23 19:01:43Z
//Please dont change the contents of this file. Otherwise IL2CPP runtime may not work with runtime monitoring!
//Ensure that this file is located in Assembly-CSharp. Otherwise this file may not compile.
//If this file contains any errors please contact me and/or create an issue in the linked repository.
//https://github.com/JohnBaracuda/Runtime-Monitoring

#if ENABLE_IL2CPP && !DISABLE_MONITORING

internal class IL2CPP_AOT
{
    //Field Profiles
    
    //FieldProfile<PlayerCtrl, bool>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.FieldProfile<PlayerCtrl, System.Boolean> AOT_GENERATED_TYPE_0;
    
    //FieldProfile<BEnemyCtrl, Transform>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.FieldProfile<BEnemyCtrl, UnityEngine.Transform> AOT_GENERATED_TYPE_2;
    
    //FieldProfile<BeAttackedable, bool>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.FieldProfile<BeAttackedable, System.Boolean> AOT_GENERATED_TYPE_4;
    
    //FieldProfile<BSaveData, List<BSaveData>>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.FieldProfile<BSaveData, System.Collections.Generic.List<BSaveData>> AOT_GENERATED_TYPE_5;
    
    //FieldProfile<Destructable, int>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.FieldProfile<Core.Combat.Destructable, System.Int32> AOT_GENERATED_TYPE_6;
    
    //FieldProfile<FPSMonitor, float>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.FieldProfile<Baracuda.Monitoring.Modules.FPSMonitor, System.Single> AOT_GENERATED_TYPE_9;
    
    //FieldProfile<SystemMonitor, string>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.FieldProfile<Baracuda.Monitoring.Modules.SystemMonitor, System.String> AOT_GENERATED_TYPE_11;

    //------------------------------------------------------------------------------------------------------------------

    //Property Profiles
    
    //PropertyProfile<PlayerCtrl, bool>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.PropertyProfile<PlayerCtrl, System.Boolean> AOT_GENERATED_TYPE_1;
    
    //PropertyProfile<BEnemyCtrl, int>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.PropertyProfile<BEnemyCtrl, System.Int32> AOT_GENERATED_TYPE_3;
    
    //PropertyProfile<ConsoleMonitor, Queue<string>>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.PropertyProfile<Baracuda.Monitoring.Modules.ConsoleMonitor, System.Collections.Generic.Queue<System.String>> AOT_GENERATED_TYPE_7;
    
    //PropertyProfile<ConsoleMonitor, string>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.PropertyProfile<Baracuda.Monitoring.Modules.ConsoleMonitor, System.String> AOT_GENERATED_TYPE_8;
    
    //PropertyProfile<FPSMonitor, int>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.PropertyProfile<Baracuda.Monitoring.Modules.FPSMonitor, System.Int32> AOT_GENERATED_TYPE_10;

    //------------------------------------------------------------------------------------------------------------------

    //Event Profiles

    //------------------------------------------------------------------------------------------------------------------

    //Method Profiles

    //------------------------------------------------------------------------------------------------------------------

    //Value Processor Method Definitions

    [UnityEngine.Scripting.PreserveAttribute]
    [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.NoOptimization)]
    private static void AOT()
    {
        Baracuda.Monitoring.IL2CPP.AOTBridge.AOTEnumerable<BSaveData>();
        Baracuda.Monitoring.IL2CPP.AOTBridge.AOTList<System.Collections.Generic.List<BSaveData>, BSaveData>();
        Baracuda.Monitoring.IL2CPP.AOTBridge.AOTEnumerable<System.String>();
    }
}

#endif //ENABLE_IL2CPP && !DISABLE_MONITORING

//----------------------------------------------------------------------------------------------------------------------

//--- Stats ---

//General

//Monitored Member:               33
//Monitored Member Instance:      32
//Monitored Member Static:         1

//MemberInfo

//Monitored Fields:               26
//Monitored Fields Instance:      25
//Monitored Fields Static:         1
//Monitored Properties:            7
//Monitored Properties Instance:   7

//Monitored Types

//Monitored bool:                  4
//Monitored float:                 1
//Monitored int:                   4
//Monitored List<BSaveData>:       1
//Monitored Queue<string>:         1
//Monitored string:               21
//Monitored Transform:             1

//----------------------------------------------------------------------------------------------------------------------

//If this file contains any errors please contact me and/or create an issue in the linked repository.
//https://github.com/JohnBaracuda/Runtime-Monitoring